menu:
    Home: /
    Archives: /archives
    Excerpt: /Excerpt
    About: /About

# fa is an widget to print how many days that fafa gone and print fafa's logo.
fa: true

vertical: false
excerpt: true
toc: true

# add update time
update: false

# Disqus comment. if comments = false then disqus won't be load
comments: false
disqus_shortname: kleist

darkmode: true
always_darkmode: false
favicon: /imgs/favicon.png
avatar:  /imgs/avatar.png
license: CC BY-NC-ND 4.0